### ISSUE TITLE
SaslAuthenticationException after installation on ICP 3.1.1

### ISSUE THREAD

**Issue by johbossle** [IBM/event-streams#18]
Hi, 
I just installed the IBM Event Streams Community Edition-2018.3.1 into a fresh installation of ICP 3.1.1 (CE) and get a `org.apache.kafka.common.errors.SaslAuthenticationException: Authentication failed, invalid credentials` when I'm trying to access the UI.
Checking the logs (as noted in https://github.com/IBM/event-streams/issues/10) lead me to the fact, that the log of the `eventstreams-ibm-es-access-controller` is full of errors like this
```
{"error":"Post https://xxx.yyy.zzz:8443/iam-token/oidc/token: x509: certificate signed by unknown authority","message":"failed to obtain token from IAM","message_template":"failed to obtain token from IAM","mh_file":"renewer.go","mh_line":104,"mh_ts":"Feb  6 07:53:09.287","transaction_id":"a8411f35-bde7-4524-9cf3-73972746908c"}
```
The installation seems to be correct, since there are no failed jobs or other obvious strange pods.
I installed the ICP with having a valid singed certificate and a custom domain name (not only published with an IP address). I also installed the eventstreams with a provided certificate/ private key (section `Kafka external access configuration` in the values.yaml).
Is there any chance to import the certificate of the iam service to a keystore, so it is considered as a valid certificate? 
Any help is highly appreciated.

**Comment by nictownsend** [comment]
Hi Johannes,

The error that you have supplied suggests that the certificate presented by the web server serving `https://xxx.yyy.zzz:8443/iam-token/oidc/token` is not providing a certificate chain that `eventstreams-ibm-es-access-controller` can verify.

Would you be able to provide the public certificate that you supplied when installing ICP, and the public certificate you supplied when installing Event Streams?

Additionally, could you provide the output from `kubectl -n kube-system get secret cluster-ca-cert -o=jsonpath='{.data.tls\.crt}' | base64 --decode | openssl x509 -text`.

Additionally, when you installed ICP, how was the certificate signed? Was it through a known CA, self signed, or signed by your own CA?

**Comment by johbossle** [comment]
Hi Nic,

I have installed the ICP with a icp-router.crt containing the complete certificate chain (according to https://www.ibm.com/support/knowledgecenter/en/SSBS6K_3.1.1/installing/create_ca_cert.html#existing). The certificate is a wildcard certificate for our domain (*.yyy.zzz) that was signed by an known CA (thawte). The management console does seamlessly work with this certificate.

For installation of eventstreams I used the following settings in ´values.yaml`
```
proxy:
  # external IP address for access that the proxy should use
  externalEndpoint: "xxx.yyy.zzz"
# Secure connection settings for the proxy
tls:
  type: "provided"
  key: "<key for my certificate | base 64>"
  cert: "<my wildcard certificate without the chain | base 64>"
  cacert: "<the chain parts of my wildcard certificate | base 64>"
```

Nevertheless the output of the `cluster-ca-cert` points to a self signed certificate. Please find it here
[kube-system.crt.txt](https://github.com/IBM/event-streams/files/2837145/kube-system.crt.txt) .

Thanks in advance
